#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;
use IO::Socket::INET;
use Socket;	# Import for networking functions

# Defaults
my $port = 514;
my $logfile = '/tmp/syslog.log';

# Get command-line options
GetOptions("port=i" => \$port, "file=s" => \$logfile) or die "Usage: $0 [--port <port_number>] [--file <CSV file>]\n";

# Create UDP socket
my $socket = IO::Socket::INET->new(
	LocalPort => $port,
	Proto => 'udp'
) or die "Could not create socket: $!\n";

print "Syslog server listening on UDP port $port...\n";

if(!-r $logfile) {
	# First run - put in the heading row
	open(my $log, '>', $logfile);
	chmod 0600, $log;
	print $log '"Host","facility","severity","msg"',
		"\n";
	close $log;
}

open(my $fout, '>>', $logfile);

while (1) {
	my $message;
	my $remote_address = $socket->recv($message, 1024);

	if ($remote_address) {
		my ($port, $ip) = unpack_sockaddr_in($remote_address);
		# my $remote_ip = inet_ntoa($ip);
		my $hostname = get_hostname_from_ip($ip);
		chomp $message;
		next if(length($message) <= 1);
		
		# Extract PRI field
		if($message =~ /^<(\d+)>(.*)/) {
			my $pri = $1;
			my $log_message = $2;

			my $facility = int($pri / 8);
			my $severity = $pri % 8;

			print $fout "\"$hostname\",$facility,$severity,\"$log_message\"\n";
		} else {
			print $fout 'Invalid message: >>', (sprintf '%v02X', $message), "<<\n";
		}
	}
	$fout->flush();
}

# Close socket (unreachable in an infinite loop)
$socket->close();

sub get_hostname_from_ip
{
	my $ip_address = shift;

	# Convert the IP address to a packed binary format
	my $packed_ip = inet_aton($ip_address);

	# If conversion fails, return undefined
	return undef unless($packed_ip);

	# Perform reverse DNS lookup
	my $hostname = gethostbyaddr($packed_ip, AF_INET);

	# Return the hostname or undefined if lookup fails
	return $hostname || undef;
}
